{
  "hash": "5e7425afdb565e78d4ec21b4592c0ad9",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Glasgow Archery League\"\nabout:\n  template: jolla\nexecute: \n  echo: false\n---\n\n::: {.cell}\n\n:::\n\n\n\n\n\n![](data/clubs.jpeg){width=\"641\"}\n\nThis is the place to keep track of what is happening in the Glasgow Archery League, organised by Iain McMillan and the clubs in the league.\n\nSee the Events tab for the scores for events that took place at each stage.\n\n## 2025/6 Schedule\n\n| Stage | Date          | Time          | Location             | What3words           |\n|-------|---------------|---------------|----------------------|----------------------|\n| 1     | 5th October   | 9AM - 1PM     | Eastwood High School | fluid.trip.tanks     |\n| 2     | 1st November  | 12PM - 4:30PM | Time Capsule         | hoping.gloves.shins  |\n| 3     | 13th December | 10AM - 2PM    | ON-X                 | lure.shredder.tribes |\n| 4     | 17th January. | 12PM - 4:30PM | Time Capsule         | hoping.gloves.shins  |\n| 5     | 21st February | 12PM - 4:30PM | Time Capsule         | hoping.gloves.shins  |\n| 6     | 21st March    | 12PM - 4:30PM | Time Capsule         | hoping.gloves.shins  |\n\n## Results\n\n| Position | Club          | Oct | Nov | Dec | Jan | Feb | Mar | Total |\n|----------|---------------|-----|-----|-----|-----|-----|-----|-------|\n| 1st      | Strathclyde   | 5   | 5   | 4   | 4   | 3   | 5   | 26    |\n| 2nd      | Glasgow       | 3   | 4   | 5   | 5   | 5   | 4   | 26    |\n| 3rd      | Monklands     | 4   | 3   | 1   | 2   | 4   | 2   | 16    |\n| 4th      | East Kilbride | 2   | 2   | 3   | 3   | 2   | 3   | 15    |\n| 5th      | Linwood       | 1   | 0   | 2   | 1   | 1   | 0   | 5     |\n| 6th      | Orion's       | 0   | 1   | 0   | 0   | 0   | 0   | 1     |\n| 7th      | Giffnock      | \\-  | \\-  | \\-  | \\-  | \\-  | 1   | 1     |\n| 8th      | UWS           | \\-  | \\-  | 0   | 0   | 0   | \\-  | 0     |\n\n\n\n::: {.cell}\n\n:::\n\n\n\n### Total Club scores for the season\n\nHere are the total scores, but it is the positions in each stage that count unless there is a tie at the end of the season.\n\nThe club scores in each tournament are for the 4 best scores (regardless of bow style).\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|Club          | Score|\n|:-------------|-----:|\n|Strathclyde   | 13133|\n|Glasgow       | 13117|\n|Monklands     | 12237|\n|East Kilbride | 11895|\n|Linwood       |  9575|\n|Orion's       |  7618|\n|UWS           |  2937|\n|Giffnock      |  1606|\n\n\n:::\n:::\n\n\n\n## League Winners\n\nThis year there was a tie between **Glasgow Archers** and **Strathclyde AC**. Therefore, total arrow scores for the top 4 archers of each club at each event was used. Strathclyde scored a total of 13,133 to Glasgow's 13,117.\n\n### The league winner is **Strathclyde Archery Club**.\n\n------------------------------------------------------------------------\n\n### League Winners 2024/5\n\nThe winner of the league for the first year was:\n\n#### Strathclyde University.\n\n## League Table\n\nThe final results are as follows, leaders at the top:\n\n| Position | Club          | Oct | Nov | Dec | Jan | Feb | Mar | Total |\n|----------|---------------|-----|-----|-----|-----|-----|-----|-------|\n| 1st      | Strathclyde   | 2   | 5   | 5   | 5   | 5   | 5   | 27    |\n| 2nd      | Glasgow       | 5   | 4   | 4   | 4   | 4   | 4   | 25    |\n| 3rd      | East Kilbride | 4   | 3   | 3   | 3   | 2   | 2   | 17    |\n| 4th      | Monklands     | 3   | 2   | 2   | 1   | 3   | 3   | 14    |\n| 5th      | Orion's       | 1   | 1   | 1   | 0   | 1   | 0   | 4     |\n| 6th      | Linwood       | 0   | 0   | 0   | 2   | 0   | 1   | 3     |\n| 7th      | UWS           | 0   | 0   | 0   | 0   | 0   | 0   | 0     |\n\n+------------------------------------+----------------+\n| Club Position in event             | Ranking points |\n|                                    |                |\n| (top four archers combined scores) |                |\n+====================================+================+\n| 1st                                | 5              |\n+------------------------------------+----------------+\n| 2nd                                | 4              |\n+------------------------------------+----------------+\n| 3rd                                | 3              |\n+------------------------------------+----------------+\n| 4th                                | 2              |\n+------------------------------------+----------------+\n| 5th                                | 1              |\n+------------------------------------+----------------+\n| All others                         | 0              |\n+------------------------------------+----------------+\n\nIf the rank totals are tied, then the total scores of the top four archers at each event are used to break the tie. In the unlikely event that these scores too are tied, then the matter cannot be settled by bows, and it is pistols at dawn.\n\nIf, at the end of a season, two clubs have the same number of match points, total arrow scores of the top four archers at each event (the same scores used for position) is used.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}